import React from 'react';
import type { ReactNode } from 'react';
import { ConfigProvider, theme } from 'antd';
import token from './../token.json'
import { flattenTokens } from './utils/utils';

interface AppConfigProviderProps {
  isDarkMode: boolean;
  children: ReactNode;
}

const AppConfigProvider: React.FC<AppConfigProviderProps> = ({ isDarkMode,children }) => {
  const flat = flattenTokens({ obj: token });
  console.log(flat)
  const lightThemeTokens = {
    token: {
      ...flat,
      // colorPrimaryBg: token.Global.Primary.Bg.value,
      // colorPrimaryBgHover: token.Global.Primary.BgHover.value,
      // colorPrimaryBorder: token.Global.Primary.Border.value,
      // colorPrimaryBorderHover: token.Global.Primary.BorderHover.value,
      // colorPrimaryHover: token.Global.Primary.Hover.value,
      // colorPrimary: token.Global.Primary.primary.value,
      // colorPrimaryActive: token.Global.Primary.Active.value,
      // colorPrimaryTextHover: token.Global.Primary.TextActive.value,
      // colorPrimaryText: token.Global.Primary.Text.value,
      // colorPrimaryTextActive: token.Global.Primary.TextActive.value,
      // colorSuccessBg: token.Global.Success.Bg.value,
      // colorSuccessBgHover: token.Global.Success.BgHover.value,
      // colorSuccessBorder: token.Global.Success.Border.value,
      // colorSuccessBorderHover: token.Global.Success.BorderHover.value,
      // colorSuccessHover: token.Global.Success.Hover.value,
      // colorSuccess: token.Global.Success.Success.value,
      // colorSuccessActive: token.Global.Success.Active.value,
      // colorSuccessTextHover: token.Global.Success.TextHover.value,
      // colorSuccessText: token.Global.Success.Text.value,
      // colorSuccessTextActive: token.Global.Success.TextActive.value,
      // colorWarningBg: token.Global.Warning.Bg.value,
      // colorWarningBgHover: token.Global.Warning.BgHover.value,
      // colorWarningBorder: token.Global.Warning.Border.value,
      // colorWarningBorderHover: token.Global.Warning.BorderHover.value,
      // colorWarningHover: token.Global.Warning.Hover.value,
      // colorWarning: token.Global.Warning.Warning.value,
      // colorWarningActive: token.Global.Warning.Active.value,
      // colorWarningTextHover: token.Global.Warning.TextHover.value,
      // colorWarningText: token.Global.Warning.Text.value,
      // colorWarningTextActive: token.Global.Warning.TextActive.value,
      // colorErrorBg: token.Global.Error.Bg.value,
      // colorErrorBgHover: token.Global.Error.BgHover.value,
      // colorErrorBorder: token.Global.Error.Border.value,
      // colorErrorBorderHover:token.Global.Error.BorderHover.value,
      // colorErrorHover: token.Global.Error.Hover.value,
      // colorError: token.Global.Error.Error.value,
      // colorErrorActive: token.Global.Error.Active.value,
      // colorErrorTextHover: token.Global.Error.TextHover.value,
      // colorErrorText: token.Global.Error.Text.value,
      // colorErrorTextActive: token.Global.Error.TextActive.value,
      // colorInfoBg: token.Global.Info.Bg.value,
      // colorInfoBgHover: token.Global.Info.BgHover.value,
      // colorInfoBorder: token.Global.Info.Border.value,
      // colorInfoBorderHover: token.Global.Info.BorderHover.value,
      // colorInfoHover: token.Global.Info.Hover.value,
      // colorInfo: token.Global.Info.Info.value,
      // colorInfoActive: token.Global.Info.Active.value,
      // colorInfoTextHover: token.Global.Info.TextHover.value,
      // colorInfoText: token.Global.Info.Text.value,
      // colorInfoTextActive: token.Global.Info.TextActive.value,
      // colorLink: token.Global.Link.Link.value,
      // colorLinkHover: token.Global.Link.Hover.value,
      // colorLinkActive: token.Global.Link.Active.value,
      // colorTextBase: token.Global.Neutral.TextBase.value,
      // colorBgBase: token.Global.Neutral.BgBase.value,
      // colorText: token.Global.Text.Text.value,
      // colorTextSecondary: token.Global.Text.Secondary.value,
      // colorTextTertiary: token.Global.Text.Tertiary.value,
      // colorTextQuaternary: token.Global.Text.Quaternary.value,
      // colorBorder: token.Global.Border.Main.value,
      // colorBorderSecondary: token.Global.Border.Secondary.value,
      // colorFill: token.Global.Fill.Main.value,
      // colorFillSecondary: token.Global.Fill.Secondary.value,
      // colorFillTertiary: token.Global.Fill.Tertiary.value,
      // colorFillQuaternary: token.Global.Fill.Quaternary.value,
      // colorBgContainer: token.Global.Bg.Container.value,
      // colorBgElevated: token.Global.Bg.Elevated.value,
      // colorBgLayout: token.Global.Bg.Layout.value,
      // colorBgSpotlight: token.Global.Bg.Spotlight.value,
      // colorBgMask: token.Global.Bg.Mask.value,
      fontSize: 13,
      fontSizeLG: 13,
      fontSizeSM: 12,
      fontSizeXL: 15,
      fontSizeHeading1: 27,
      fontSizeHeading2: 23,
      fontSizeHeading3: 19,
      fontSizeHeading4: 15,
      fontSizeHeading5: 13,
      lineHeight: 1.9,
      lineHeightSM: 2.1,
      lineHeightLG: 1.7,
      lineHeightHeading1: 1.4,
      lineHeightHeading2: 1.425,
      lineHeightHeading3: 1.45,
      lineHeightHeading4: 1.58,
      lineHeightHeading5: 1.7,
      sizeStep: 5,
      sizeUnit: 5,
      marginXXS: 11,
      marginXS: 11,
      marginSM: 16,
      margin: 16,
      marginMD: 26,
      marginLG: 24,
      marginXL: 32,
      marginXXL: 32,
      paddingXXS: 11,
      paddingXS: 11,
      paddingSM: 16,
      padding: 16,
      paddingMD: 26,
      paddingLG: 27,
      paddingXL: 32,
      borderRadiusXS: 3,
      borderRadius: 7,
      borderRadiusSM: 6,
      borderRadiusLG: 10,
      boxShadow: "\n      0 6px 15px 0 rgba(0, 0, 0, 0.08),\n      0 3px 6px -4px rgba(0, 0, 0, 0.12),\n      0 9px 28px 8px rgba(0, 0, 0, 0.05)\n    ",
      boxShadowSecondary: "\n      0 6px 15px 0 rgba(0, 0, 0, 0.08),\n      0 3px 6px -4px rgba(0, 0, 0, 0.12),\n      0 9px 28px 8px rgba(0, 0, 0, 0.05)\n    ",
      wireframe: true
    },
  };

  const darkThemeTokens = {
    token: {
      // colorPrimaryBg: token.Global.Primary.Bg.value,
      // colorPrimaryBgHover: token.Global.Primary.BgHover.value,
      // colorPrimaryBorder: token.Global.Primary.Border.value,
      // colorPrimaryBorderHover: token.Global.Primary.BorderHover.value,
      // colorPrimaryHover: token.Global.Primary.Hover.value,
      // colorPrimary: token.Global.Primary.primary.value,
      // colorPrimaryActive: token.Global.Primary.Active.value,
      // colorPrimaryTextHover: token.Global.Primary.TextActive.value,
      // colorPrimaryText: token.Global.Primary.Text.value,
      // colorPrimaryTextActive: token.Global.Primary.TextActive.value,
      // colorSuccessBg: token.Global.Success.Bg.value,
      // colorSuccessBgHover: token.Global.Success.BgHover.value,
      // colorSuccessBorder: token.Global.Success.Border.value,
      // colorSuccessBorderHover: token.Global.Success.BorderHover.value,
      // colorSuccessHover: token.Global.Success.Hover.value,
      // colorSuccess: token.Global.Success.Success.value,
      // colorSuccessActive: token.Global.Success.Active.value,
      // colorSuccessTextHover: token.Global.Success.TextHover.value,
      // colorSuccessText: token.Global.Success.Text.value,
      // colorSuccessTextActive: token.Global.Success.TextActive.value,
      // colorWarningBg: token.Global.Warning.Bg.value,
      // colorWarningBgHover: token.Global.Warning.BgHover.value,
      // colorWarningBorder: token.Global.Warning.Border.value,
      // colorWarningBorderHover: token.Global.Warning.BorderHover.value,
      // colorWarningHover: token.Global.Warning.Hover.value,
      // colorWarning: token.Global.Warning.Warning.value,
      // colorWarningActive: token.Global.Warning.Active.value,
      // colorWarningTextHover: token.Global.Warning.TextHover.value,
      // colorWarningText: token.Global.Warning.Text.value,
      // colorWarningTextActive: token.Global.Warning.TextActive.value,
      // colorErrorBg: token.Global.Error.Bg.value,
      // colorErrorBgHover: token.Global.Error.BgHover.value,
      // colorErrorBorder: token.Global.Error.Border.value,
      // colorErrorBorderHover:token.Global.Error.BorderHover.value,
      // colorErrorHover: token.Global.Error.Hover.value,
      // colorError: token.Global.Error.Error.value,
      // colorErrorActive: token.Global.Error.Active.value,
      // colorErrorTextHover: token.Global.Error.TextHover.value,
      // colorErrorText: token.Global.Error.Text.value,
      // colorErrorTextActive: token.Global.Error.TextActive.value,
      // colorInfoBg: token.Global.Info.Bg.value,
      // colorInfoBgHover: token.Global.Info.BgHover.value,
      // colorInfoBorder: token.Global.Info.Border.value,
      // colorInfoBorderHover: token.Global.Info.BorderHover.value,
      // colorInfoHover: token.Global.Info.Hover.value,
      // colorInfo: token.Global.Info.Info.value,
      // colorInfoActive: token.Global.Info.Active.value,
      // colorInfoTextHover: token.Global.Info.TextHover.value,
      // colorInfoText: token.Global.Info.Text.value,
      // colorInfoTextActive: token.Global.Info.TextActive.value,
      // colorLink: token.Global.Link.Link.value,
      // colorLinkHover: token.Global.Link.Hover.value,
      // colorLinkActive: token.Global.Link.Active.value,
      // colorTextBase: token.Global.Neutral.TextBase.value,
      // colorBgBase: token.Global.Neutral.BgBase.value,
      // colorText: token.Global.Text.Text.value,
      // colorTextSecondary: token.Global.Text.Secondary.value,
      // colorTextTertiary: token.Global.Text.Tertiary.value,
      // colorTextQuaternary: token.Global.Text.Quaternary.value,
      // colorBorder: token.Global.Border.Main.value,
      // colorBorderSecondary: token.Global.Border.Secondary.value,
      // colorFill: token.Global.Fill.Main.value,
      // colorFillSecondary: token.Global.Fill.Secondary.value,
      // colorFillTertiary: token.Global.Fill.Tertiary.value,
      // colorFillQuaternary: token.Global.Fill.Quaternary.value,
      // colorBgContainer: token.Global.Bg.Container.value,
      // colorBgElevated: token.Global.Bg.Elevated.value,
      // colorBgLayout: token.Global.Bg.Layout.value,
      // colorBgSpotlight: token.Global.Bg.Spotlight.value,
      // colorBgMask: token.Global.Bg.Mask.value,
      fontSize: 13,
      fontSizeLG: 13,
      fontSizeSM: 12,
      fontSizeXL: 15,
      fontSizeHeading1: 27,
      fontSizeHeading2: 23,
      fontSizeHeading3: 19,
      fontSizeHeading4: 15,
      fontSizeHeading5: 13,
      lineHeight: 1.9,
      lineHeightSM: 2.1,
      lineHeightLG: 1.7,
      lineHeightHeading1: 1.4,
      lineHeightHeading2: 1.425,
      lineHeightHeading3: 1.45,
      lineHeightHeading4: 1.58,
      lineHeightHeading5: 1.7,
      sizeStep: 5,
      sizeUnit: 5,
      marginXXS: 11,
      marginXS: 11,
      marginSM: 16,
      margin: 16,
      marginMD: 26,
      marginLG: 24,
      marginXL: 32,
      marginXXL: 32,
      paddingXXS: 11,
      paddingXS: 11,
      paddingSM: 16,
      padding: 16,
      paddingMD: 26,
      paddingLG: 27,
      paddingXL: 32,
      borderRadiusXS: 3,
      borderRadius: 7,
      borderRadiusSM: 6,
      borderRadiusLG: 10,
      boxShadow: "\n      0 6px 15px 0 rgba(0, 0, 0, 0.08),\n      0 3px 6px -4px rgba(0, 0, 0, 0.12),\n      0 9px 28px 8px rgba(0, 0, 0, 0.05)\n    ",
      boxShadowSecondary: "\n      0 6px 15px 0 rgba(0, 0, 0, 0.08),\n      0 3px 6px -4px rgba(0, 0, 0, 0.12),\n      0 9px 28px 8px rgba(0, 0, 0, 0.05)\n    ",
      wireframe: true
    },
  };

  return (
    <ConfigProvider
      theme={{
        algorithm: isDarkMode ? theme.darkAlgorithm : theme.defaultAlgorithm,
        token: isDarkMode ? darkThemeTokens.token : lightThemeTokens.token,
      }}  
    >
      {children}
    </ConfigProvider>
  );
};

export default AppConfigProvider;